### ISSUE TITLE
Implementation of BALD and BatchBALD pool based query strategy

### ISSUE THREAD

**Issue by Pascal112** [scikit-activeml/scikit-activeml#275]
BALD:
https://arxiv.org/pdf/1112.5745.pdf
BatchBALD:
https://arxiv.org/pdf/1906.08158.pdf
https://github.com/BlackHC/batchbald_redux/blob/master/batchbald_redux/batchbald.py

**Comment by BedirT** [comment]
I noticed that these features have already been implemented. Why is the issue still open?

**Comment by mherde** [comment]
Hello @BedirT

Thanks for your friendly hint. Yes, these features have been indeed implemented such that we will close this issue. However, for your potential interest, we will continue our work in this direction since we aim to ease the support of deep learning models in our framework, particularly in combination with deep active learning methods such as `BatchBALD`.
